name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
            
            - uses: actions/checkout@v3
              with:
                submodules: true
                fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '22'

            - name: Install Dependencies
              run: npm install

            - name: Build React App
              run: npm run build

            - uses: nekitcorp/yandex-storage-website-action@v2
              with:
                  access-key-id: ${{ secrets.ACCESS_KEY_ID }}
                  secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
                  bucket: ${{ secrets.BUCKET }}
                  working-directory: build
                  clear: true
